Configuration
dokc/how-to-dok pull request #18
Opened 2021-09-21 16:17 UTC by AbhijithGanesh

Addition of Configuration file for k8ssandra.yml

Addresses feature ticket #16

2021-09-23 06:53 UTC, patchandpray commented on config/k8ssandra.yaml
> +cassandra:
Hey @AbhijithGanesh I am missing some context here for this file:

In my head it goes like this:
So now we have a config directory, what is the config directory for?
Ok I see a k8ssandra.yaml, how is it used, why do we need it? What do these options in the file mean?
If I want to start using this file what do I need to do?
How was the file created?

this is all very helpful and relevant information to give context to this single file. Without it a new user does not know what to do with this file.

2021-09-23 06:58 UTC, AbhijithGanesh commented on config/k8ssandra.yaml
> +cassandra:
The config directory will have the files for environments which our developers intend to use, like they will contain the yml/yaml files which would aid them in creating a local/cloud cluster.

- If you want to start using this file.... it is a sequential process which I will be writing on, I uploaded this as an early head up
- The file was taken from the official k8s docs.
- The options in the file deal with specifics such as version, datacenter on which this cluster will be deployed,etc.
- I do understand it is kind of early to make complete sense of this but this file is a part of the installation process/ blog which I will be writing(on how to estabish a k8ssandra cluster)

2021-09-27 04:10 UTC, AbhijithGanesh commented on config/k8ssandra.yaml
> +cassandra:
@patchandpray is that fine?

2021-10-04 07:02 UTC, patchandpray commented on config/k8ssandra.yaml
> +cassandra:
Hey @AbhijithGanesh, I was out :) I really think that just a file without some context is confusing. can you add a README.md to the /config directory in which you add for example: information that this file was taken from the official k8s docs, that this file can be used to deal with specifics version, and that more information about this file will follow. In that case it would be fine for me. Just a config file without any context about what it is doing in the repository is something we should try to avoid :)

2021-10-04 07:05 UTC, patchandpray commented on .github/ISSUE_TEMPLATE/idea.yml
>  description: Suggest your issue here🥇
The name is idea but the description says suggest your issue. Shouldn't it be suggest your idea here?

2021-10-04 07:05 UTC, patchandpray commented on .github/ISSUE_TEMPLATE/idea.yml
> +title: "[IDEA]: Your Issue's brief Description goes here"
Same here, it says Issue but shouldnt it be Idea?

2021-12-01 04:20 UTC, helper-uttam requested changes

2021-12-01 04:20 UTC, helper-uttam commented on config/k8ssandra.yaml
> +  cpuLimMillicores: 1000
I think in last, a blank line is required!

2021-12-01 05:30 UTC, kaiwalyakoparkar commented on config/k8ssandra.yaml
> +  cpuLimMillicores: 1000
That's not compulsory though.

2022-01-28 09:44 UTC, AbhijithGanesh commented
@patchandpray I have resolved the readme file

2022-01-28 09:44 UTC, AbhijithGanesh commented
Idea.yml doesn't exist, so I have created one.

2022-01-29 06:56 UTC, AbhijithGanesh commented
Sure, I will make another PR

2022-01-29 11:35 UTC, closed without merging