Updated RESOURCES.md
dokc/how-to-dok pull request #52
Opened 2021-12-06 16:48 UTC by yashgangwar7558

Added a resource for K8ssandra and how we can connect Cassandra to Kubernetes using K8ssandra.

Addresses issue #25

2021-12-07 05:07 UTC, kaiwalyakoparkar requested changes

2021-12-07 05:07 UTC, kaiwalyakoparkar commented on RESOURCES.md
> +- ### K8ssandra
Please add this section after Kubernetes resources

2021-12-07 07:47 UTC, patchandpray commented on RESOURCES.md
> +- ### K8ssandra
Agreed, @yashgangwar7558 to have this come after the kubernetes header is more logical :)

2021-12-08 04:36 UTC, yashgangwar7558 commented
@kaiwalyakoparkar @patchandpray I have made the suggested changes.

2021-12-08 07:55 UTC, patchandpray approved these changes

2021-12-08 07:55 UTC, patchandpray commented
@kaiwalyakoparkar you requested changes, are the changes ok for you now? it is blocking merging :)

2021-12-08 13:07 UTC, kaiwalyakoparkar approved these changes
lgtm

2021-12-08 13:08 UTC, merged