Create Intro-to-Cloud-Native.md
dokc/how-to-dok pull request #60
Opened 2021-12-21 17:49 UTC by AmitKarnam

Started to work on the Introductory reading materials , required for new comers in the community . 
Added notes on introduction to cloud native.

2021-12-22 05:24 UTC, helper-uttam approved these changes
I've reviewed the article and made some changes. I loved the article it was great :)

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +***The Cloud Native Computing Foundation(CNCF)***  defines Cloud Native as technologies empower organizations to build and run scalable applications in modern, dynamic environments such as public, pr
```diff
- defines Cloud Native as technologies empower 
+ defines Cloud Native as technologies that empower 
```

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +1) Cloud-native applications are different from the traditional applications that run in our data centres. The applications that are designed in the traditional way are not built keeping cloud compat
```diff
-  data centres
+ data centers
- that are designed in the traditional way
+ that are designed traditionally
```

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +2) So, we need a new architecture for our applications to utilize the benefits of cloud. There is a need to design the applications keeping cloud in mind and take advantage of several services the cl
```diff
- cloud
+ the cloud
```
Note:- There are 2 "cloud" which needs to be replaced

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +Some of the various service included with cloud :
```diff
- service included with cloud
+ services included with a cloud 
```

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +- Value added cloud services
```diff
- Value added
+ Value-added
```

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +1) Isolation refers to the fact that a small part of rather large application can be built in isolation , and many such isolated parts together constitute of the application. These isolated parts of
```diff
- part of rather large application can be built in isolation , and many such isolated parts together constitute of the application. These isolated parts of the application communicate over the network, most commonly using API's.
+ part of a rather large application can be built in isolation, and many such isolated parts together constitute the application. These isolated parts of the application communicate over the network, most commonly using an API.
```

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +2) The ability to create parts ( microservices ) of a large application in isolation helps in many factors of development and operations for example scalability,debugging etc.
```diff
- scalability,debugging etc.
+  scalability, debugging, etc.
```

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +1) Simply deploying your application on cloud does not make it cloud-native. To be cloud native it should be able to take full benefits of the cloud. One of the key features would be Scalability.
```diff
- Simply deploying your application on cloud does not make it cloud-native. To be cloud native it should be able to take full benefits of the cloud. One of the key features would be Scalability.
+ Simply deploying your application on the cloud does not make it cloud-native. To be cloud-native it should be able to take full benefits of the cloud. One of the key features would be Scalability.
```

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +2) In today's dynamic word it is not quite enough for the application to just perform as intended, but it should be able to handle the fluctuating traffic it recieves, i.e. **Ability to handle sudden
```diff
- word 
+ world
-  recieves, i.e.  Ability to handle sudden increase in traffic, In such cases the application
+ receives, i.e. Ability to handle a sudden increase in traffic, In such cases, the application
```

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +3) To achieve this, cloud native application runs in multiple runtimes spread across multiple hosts. The applications should be designed and architected in a way that they support multi regional, act
```diff
- To achieve this, cloud native application runs in multiple runtimes spread across multiple hosts. The applications should be designed and architected in a way that they support multi regional, active-active deployments.
+ To achieve this, a cloud-native application runs in multiple runtimes spread across multiple hosts. The applications should be designed and architected in a way that supports multi-regional, active-active deployments.
```

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +1) By using the value added services provided by the cloud provider, we will get to know all the available options on the cloud and we can also learn about all the new services. This will help us to
```diff
- value added 
+ value-added
```

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +- [CNCF's What is cloud native and why does it exists](https://youtu.be/d_8Vly4_ofo)
```diff
- CNCF's What is cloud native and why does it exists
+ CNCF's What is cloud-native and why does it exist
```
I loved it :) Keep growing Amit

2021-12-22 05:24 UTC, helper-uttam commented on Reading-Materials/Intro-to-Cloud-Native.md
> +- [IBM's introduction to cloud native article](https://ibm.github.io/cloud-enterprise-examples/concepts/cloud-native-overview/)
```diff
- IBM's introduction to cloud native article
+ IBM's introduction to cloud-native article
```

2021-12-22 15:29 UTC, kaiwalyakoparkar requested changes
please make the requested changed by @helper-uttam

2021-12-22 17:10 UTC, AmitKarnam commented
I have made the all the changes suggested by @helper-uttam , Why does it say I dismissed  @helper-uttam 's stale review? When I made all the changes.

2021-12-22 17:37 UTC, helper-uttam commented
> I have made the all the changes suggested by @helper-uttam , Why does it say I dismissed @helper-uttam 's stale review? When I made all the changes.

I think that's because I had approved the changes after reviewing and suggesting changes. I should I've requested changes but no worries :) I'll give it an approval once more xD

2021-12-22 17:44 UTC, helper-uttam requested changes
Need many changes eg:- line 23.
```diff
- clou- native
+ cloud-native 
```

2022-01-19 02:55 UTC, closed without merging

2022-01-19 02:57 UTC, AmitKarnam commented
I am closing this pull request as I messed up the changes part, I will be now opening a new PR shortly to handle this issue.