Yml provisioning
dokc/how-to-dok pull request #80
Opened 2022-01-27 15:15 UTC by AbhijithGanesh

Addition of YML provisions to allow ingest to Cassandra DB.

2022-02-01 07:27 UTC, patchandpray commented on yaml-provisioning/readme.md
> +Follow the format mentioned in the `format.yml` to parse data.
Hey, I don't understand this. How can I use these files together? Can you add a step by step instruction of how I can use this on my machine or what I can use it for?

Imagine I open this directory for the first time and I get this Readme, what would I want to know about the files in this directory?
- what are they
- what can they be used for
- how can I use them

2022-02-03 10:06 UTC, AbhijithGanesh commented
Closes #5

2022-02-04 06:06 UTC, shreemaan-abhishek commented on yaml-provisioning/readme.md
> +Follow the format mentioned in the `format.yml` to parse data.
@AbhijithGanesh

2022-02-04 06:21 UTC, AbhijithGanesh commented on yaml-provisioning/readme.md
> +Follow the format mentioned in the `format.yml` to parse data.
Changed !

2022-02-04 08:33 UTC, patchandpray commented on yaml-provisioning/readme.md
> +The file will be parsed by the [parser-script](https://github.com/AbhijithGanesh/how-to-dok/blob/yml-provisioning/yaml-provisioning/parser.js) which will parse the data and convert it into JSON for e
You can also create a link to a file in the directory, that is neater than referring a file from a different repository since the file is already locally here aswell ie: `[parser-script](parser.js)`

2022-02-04 08:34 UTC, AbhijithGanesh commented on yaml-provisioning/readme.md
> +The file will be parsed by the [parser-script](https://github.com/AbhijithGanesh/how-to-dok/blob/yml-provisioning/yaml-provisioning/parser.js) which will parse the data and convert it into JSON for e
Sure

2022-02-05 08:26 UTC, AbhijithGanesh reviewed
@AmitKarnam and @yashgangwar7558 Can you guys look into my YAML provisioning?

2022-02-05 12:01 UTC, yashgangwar7558 requested changes
I tried out, and its working perfectly fyn. Just one suggestion maybe we can add one more field of "written_by/lyrics_by" after "singer".

2022-02-08 08:49 UTC, patchandpray approved these changes

2022-02-08 09:47 UTC, merged