Addition of an Issue yml
dokc/how-to-dok pull request #9
Opened 2021-09-09 17:56 UTC by AbhijithGanesh

This attempts to solve issue #38. This contains issue.yml. Once approved, I shall make templates for Ideas, bugs and Q and A

2021-09-10 15:42 UTC, kaiwalyakoparkar commented
@AbhijithGanesh could you please enable issues on your fork so that I can test it?

2021-09-10 15:48 UTC, AbhijithGanesh commented
Yes

2021-09-11 04:32 UTC, kaiwalyakoparkar requested changes

2021-09-11 04:32 UTC, kaiwalyakoparkar commented on .github/ISSUE_TEMPLATE/issue.yml
> +name: Issue Template❌
Replace the ❌ with some generic emoji which matches the name of the issue

2021-09-11 07:39 UTC, verma-kunal commented
@patchandpray , I am actually not that much familiar with `yaml` right now (would have to learn) !! 
but i can definitely give a **`lgtm`** after you and @kaiwalyakoparkar would have reviewed this 🙂

2021-09-12 09:57 UTC, kaiwalyakoparkar commented
> @patchandpray , I am actually not that much familiar with `yaml` right now (would have to learn) !!
> but i can give a **`lgtm`** after you and @kaiwalyakoparkar would have reviewed this

Yeah, it's good but I suggested for some changes in emoji

2021-09-13 15:33 UTC, patchandpray commented on .github/ISSUE_TEMPLATE/issue.yml
> +name: Issue Template❌
Which emoji did you have in mind. The X does symbolise something beeing an issue so IMO it can be a good fit

2021-09-13 15:33 UTC, patchandpray approved these changes

2021-09-13 15:40 UTC, patchandpray commented
> @patchandpray , I am actually not that much familiar with `yaml` right now (would have to learn) !!
> but i can give a **`lgtm`** after you and @kaiwalyakoparkar would have reviewed this

That is fine, YAML stands for Yet Another Markup Language and is a very human friendly (well readable) yet still powerful (supports macros) configuration language. https://circleci.com/blog/what-is-yaml-a-beginner-s-guide/

Kubernetes resources are often defined with YAML as well. (although json is also supported as a configuration language)

2021-09-15 04:44 UTC, verma-kunal commented
> > @patchandpray , I am actually not that much familiar with `yaml` right now (would have to learn) !!
> > but i can give a **`lgtm`** after you and @kaiwalyakoparkar would have reviewed this
> 
> That is fine, YAML stands for Yet Another Markup Language and is a very human friendly (well readable) yet still powerful (supports macros) configuration language. https://circleci.com/blog/what-is-yaml-a-beginner-s-guide/
> 
> Kubernetes resources are often defined with YAML as well. (although json is also supported as a configuration language)

thanks!! I am learning this right now, as there is a lot of use of YAML these days, from what i have observed. in DevOps & on GitHub as well

2021-09-15 04:46 UTC, verma-kunal commented on .github/ISSUE_TEMPLATE/issue.yml
> +name: Issue Template❌
i was thinking, do we need to put emojis in all of these!! everything is clear from the name itself, right?

2021-09-15 14:28 UTC, kaiwalyakoparkar commented on .github/ISSUE_TEMPLATE/issue.yml
> +name: Issue Template❌
Yes, I insisted him the same :)

2021-09-15 14:29 UTC, kaiwalyakoparkar approved these changes
lgtm

2021-09-15 14:31 UTC, merged