spelling correction
dokc/how-to-dok pull request #96
Opened 2022-02-09 08:51 UTC by shefali12-ab

I have corrected the spelling of some of the .md files.

2022-02-09 10:45 UTC, AbhijithGanesh requested changes

2022-02-09 10:45 UTC, AbhijithGanesh commented on CODE_OF_CONDUCT.md
> +[mozilla coc]: https://github.com/mozilla/diversity
It'd be better if these words are capitalized the same way.

2022-02-09 10:45 UTC, AbhijithGanesh commented on resources/Introduction-to-Cloud-Native.md
> +### **What is Cloud Native?** <hr/>
The `<hr/>` is not required.

2022-02-09 10:45 UTC, AbhijithGanesh commented on resources/Introduction-to-Cloud-Native.md
> +**_The Cloud Native Computing Foundation(CNCF)_** defines Cloud Native as technologies that empower organizations to build and run scalable applications in modern, dynamic environments
*** and **_ in symbol does the same thing.

2022-02-09 10:45 UTC, AbhijithGanesh commented on resources/Introduction-to-Cloud-Native.md
> +### **Need for cloud-native** <hr/>
Again, `<hr/>` is not required.

2022-02-09 10:45 UTC, AbhijithGanesh commented on resources/cloud_native_architecture.md
> +Now that we know about the principles of cloud-native architecture, we now move to discuss a bit more about application architecture for the cloud.
This is a good catch, I think this patch is good.

2022-02-09 10:45 UTC, AbhijithGanesh commented on resources/cloud_native_architecture.md
> +
Can you remove the <hr> as mentioned above?

2022-02-09 10:45 UTC, AbhijithGanesh commented on resources/run-k8ssandra-on-k3d-locally-lightweight/run-k8ssandra-on-k3d-locally-lightweight.md
> +When following the boilerplate k8ssandra.io installation guide we get a full blown cluster with monitoring and all the bangs and whistles with minimum effort. But this adds on a lot of additional fea
Good catch!

2022-02-09 10:45 UTC, AbhijithGanesh commented on resources/run-k8ssandra-on-k3d-locally-lightweight/run-k8ssandra-on-k3d-locally-lightweight.md
> +Next up it is time to create a minimal example of a cassandra datacentre. For this we take the example-cassdc-minimal.yaml from https://raw.githubusercontent.com/k8ssandra/cass-operator/master/operat
Please revert it back to `datacenter`

2022-02-09 14:18 UTC, shefali12-ab commented on resources/cloud_native_architecture.md
> +
yeah sure

2022-02-09 14:29 UTC, shefali12-ab commented
@AbhijithGanesh I have done the changes, it is having resolve the conflict please check what to include.

2022-02-09 19:18 UTC, AbhijithGanesh approved these changes

2022-02-10 03:04 UTC, Vrukshali-26 commented
LGTM🚀

2022-02-10 03:05 UTC, Vrukshali-26 approved these changes
LGTM🚀

2022-02-10 04:40 UTC, merged

2022-02-10 04:41 UTC, shreemaan-abhishek approved these changes